[package]
name = "installer"
version = "0.1.1"
rust-version = "1.95.0"
edition = "2024"

[dependencies]
firefly-keyboard = "0.1.4"
firefly-rust = { version = "0.15.0", features = ["talc"] }
firefly-sudo = { version = "0.14.3", features = ["alloc"] }
firefly-ui = "0.3.2"
firefly-types = "0.11.0"
# Updating sha2 to 0.11.0 adds 4kb to the binary size.
# The changelog doesn't provide a good explanation on why it might be.
# So, why update? If it works, it works.
sha2 = { version = "0.10.9", default-features = false }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "s" # Optimize for speed.
lto = true      # Enable link-time optimization
