[package]
name = "installer"
version = "0.1.0"
edition = "2024"

[dependencies]
firefly-keyboard = "0.1.1"
firefly-rust = { version = "0.13.0", features = ["alloc", "talc", "sudo"] }
firefly-ui = "0.1.0"

[patch.crates-io]
firefly-rust = { path = "../firefly-rust" }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true      # Enable link-time optimization
