[package]
name = "installer"
version = "0.1.1"
rust-version = "1.95.0"
edition = "2024"

[dependencies]
firefly-keyboard = "0.1.2"
firefly-rust = { version = "0.13.2", features = ["alloc", "talc", "sudo"] }
firefly-ui = "0.2.0"
firefly-types = "0.10.0"
# Updating sha2 to 0.11.0 adds 4kb to the binary size.
# The changelog doesn't provide a good explanation on why it might be.
# So, why update? If it works, it works.
sha2 = { version = "0.11.0", default-features = false }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true      # Enable link-time optimization
